Added hyperlink to slide deck
service-mesh-performance/service-mesh-performance pull request #230
Opened 2021-08-20 08:45 UTC by soham4abc

Signed-off-by: Soham Banerjee <sohambanerjee4abc@hotmail.com>

**Description**
Added hyperlink to slide underneath the preview
This PR fixes #228

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-08-20 09:13 UTC, warunicorn19 approved these changes
LGTM🎉, thanks @soham4abc

2021-08-20 16:43 UTC, soham4abc commented
@leecalcote please do have a look!

2021-08-20 18:59 UTC, leecalcote commented
Thank you, @soham4abc. A small request: will you place this outside of the modal or will you ensure that the link changes color or activates in some way?

2021-08-20 19:00 UTC, leecalcote commented
While you're in here, will you add links to the other slides, too?

- https://calcotestudios.com/talks/decks/slides-kubecon-eu-2020-discreetly-studying-the-effects-of-individual-traffic-control-functions.html
- https://calcotestudios.com/talks/decks/slides-kubecon-eu-2019-service-meshes-at-what-cost.html

2021-08-21 03:53 UTC, soham4abc commented
> Thank you, @soham4abc. A small request: will you place this outside of the modal or will you ensure that the link changes color or activates in some way?

I could not get your point! 
"Activates in some other way" means?

2021-08-21 06:16 UTC, warunicorn19 commented
Hey @soham4abc, so basically you would have to add like a hover effect to the link to make it understandable that it's clickable, or make it a specific colour and give it an underline to make the user understand that this can be clicked.

2021-08-21 10:36 UTC, soham4abc commented
> Hey @soham4abc, so basically you would have to add like a hover effect to the link to make it understandable that it's clickable, or make it a specific colour and give it an underline to make the user understand that this can be clicked.

done please have a look

2021-08-21 10:37 UTC, soham4abc commented
> While you're in here, will you add links to the other slides, too?
> 
> * https://calcotestudios.com/talks/decks/slides-kubecon-eu-2020-discreetly-studying-the-effects-of-individual-traffic-control-functions.html
> * https://calcotestudios.com/talks/decks/slides-kubecon-eu-2019-service-meshes-at-what-cost.html

Should I do this in the same PR?

2021-08-21 10:42 UTC, warunicorn19 commented
Yes sir.

2021-08-25 04:48 UTC, soham4abc commented
@leecalcote  @warunicorn19  All Done please do have a look !

2021-08-25 04:53 UTC, leecalcote commented
Close, but no cigar. ;)

@NikhilSharma03, I wonder if you might offer some feedback.

2021-08-25 05:22 UTC, soham4abc commented
> Close, but no cigar. ;)
> 
> @NikhilSharma03, I wonder if you might offer some feedback.

should I just keep the background completely rectangular then?

2021-08-25 06:02 UTC, NikhilSharma03 commented
@soham4abc Please avoid using inline styling, instead doing it in scss file would be better. I think we can give a bit more padding around the button and decrease the `border-radius` (4px looks good on my browser.) . Also, I think adding the hover effect would be an improvement.

2021-08-25 06:12 UTC, soham4abc commented
> @soham4abc Please avoid using inline styling, instead doing it in scss file would be better. I think we can give a bit more padding around the button and decrease the `border-radius` (4px looks good on my browser.) . Also, I think adding the hover effect would be an improvement.

okay I am on it!

2021-08-25 06:38 UTC, soham4abc commented
@NikhilSharma03 @leecalcote  Please do have a look!

2021-08-25 12:19 UTC, NikhilSharma03 commented
@soham4abc It looks better now. I wonder if we can add a bit of margin between slides and button in project section. @warunicorn19 What are your thoughts. Any other changes we can add?

2021-08-25 12:32 UTC, warunicorn19 commented
Yes, please add some margin between them and the yellow doesn't match our colour scheme, try using the yellow from the `SMP IN-ACTION` button.

2021-08-25 13:12 UTC, soham4abc commented
Changes done as per request. Please do have a look! 
@leecalcote 
@warunicorn19 
@NikhilSharma03

2021-08-25 13:33 UTC, debo19 requested changes
Hey @soham4abc  thanks for the effort.Just some minor tweaks, then this should be good to go. Instead of just the text we can make the entire button have the hover effect similar to the `SMP in-action` button on the page. Also, you can remove the underline from the text.  And please move the button outside the presentation modal.

2021-08-25 13:59 UTC, soham4abc commented
I am encountering a weird problem here. In order to remove underline `text-decoration:none` is not working!

2021-08-25 14:06 UTC, debo19 commented
@soham4abc removing the `<u></u>` tag should work

2021-08-25 14:10 UTC, soham4abc commented
> @soham4abc removing the `<u></u>` tag should work

Thank you! Silly me :'-)

2021-08-25 14:13 UTC, soham4abc commented
Changes done as per request. Please do have a look!
@leecalcote
@warunicorn19
@NikhilSharma03
@debo19

2021-08-25 14:20 UTC, warunicorn19 commented
<img width="969" alt="Screenshot 2021-08-25 at 7 47 54 PM" src="https://user-images.githubusercontent.com/53532328/130807675-27f892c5-5211-4569-9532-9eb10bc7e5c7.png">

I hate to keep doing this, but could please align these together, the same has happened with the slides below, if you could align them together, it would be great😃.

2021-08-25 14:22 UTC, soham4abc commented
> <img width="969" alt="Screenshot 2021-08-25 at 7 47 54 PM" src="https://user-images.githubusercontent.com/53532328/130807675-27f892c5-5211-4569-9532-9eb10bc7e5c7.png">
> 
> I hate to keep doing this, but could please align these together, the same has happened with the slides below, if you could align them together, it would be great😃.

Sure no problem

2021-08-25 14:35 UTC, soham4abc commented
@warunicorn19  It's done as per your request please do have a look!

2021-08-29 13:26 UTC, soham4abc commented
@leecalcote  Please do have a look!

2021-09-02 19:23 UTC, leecalcote commented
@soham4abc thanks for this reminder. I'm buried in GitHub notifications. // @Jashpatel1

2021-09-02 19:24 UTC, leecalcote commented
@soham4abc if you will make the word "Slides" a hyperlink, I think this is all that we're looking for here.

2021-09-05 08:38 UTC, soham4abc commented
> @soham4abc if you will make the word "Slides" a hyperlink, I think this is all that we're looking for here.

That means the `get presentations here` is not needed right?

2021-09-05 08:54 UTC, soham4abc commented
@leecalcote  Please do have a look please!

2021-09-09 05:46 UTC, soham4abc commented
@leecalcote  Do have a look Please!

2021-09-12 09:54 UTC, soham4abc commented
@leecalcote  any more changes required?

2021-09-17 16:52 UTC, leecalcote approved these changes

2021-09-17 16:52 UTC, leecalcote commented on docs/_includes/about.html
> +              <a class="btn-slides" href="https://docs.google.com/presentation/d/1fm7Eu1T3JSBPVmdFYyyevqQLSmAMLXqzWqC7QxTHGX8/edit#" target="_blank" >Get the presentation here</a>
```suggestion
              <a class="btn-slides" href="https://docs.google.com/presentation/d/1fm7Eu1T3JSBPVmdFYyyevqQLSmAMLXqzWqC7QxTHGX8/edit#" target="_blank" >Slides</a> 
```

2021-09-17 16:53 UTC, leecalcote commented
Thank you, @soham4abc 🥇

2021-09-17 16:53 UTC, merged