Dashboard updates
service-mesh-performance/service-mesh-performance pull request #342
Opened 2022-06-12 17:55 UTC by asubedy

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-06-12 17:58 UTC, asubedy commented
Ok wait do-not merge pagination on deploy is not working, It is working perfectly in my local build. Need to look into this.

2022-06-13 17:17 UTC, warunicorn19 requested changes
- Could you add an empty state when there's no results in the table? 

<img width="1680" alt="Screenshot 2022-06-13 at 10 43 44 PM" src="https://user-images.githubusercontent.com/53532328/173408609-f53c6e2c-f883-4564-a625-3f110e372da7.png">

- Also, I think the chevron should be sticky. Otherwise it gets lost when the drawer is closed.
<img width="1680" alt="Screenshot 2022-06-13 at 10 44 29 PM" src="https://user-images.githubusercontent.com/53532328/173408715-209a4966-a266-420e-bafe-6e7e64830c0d.png">

- Also probably a different color for the sidebar? Maybe a lighter shade of the same color.

2022-06-13 17:18 UTC, warunicorn19 commented on docs/assets/js/profiles.js
> +console.log(window.location.pathname.includes("#"))
console logs can be removed.

2022-07-05 06:18 UTC, asubedy commented
I guess this is ready to merge @leecalcote @warunicorn19 ? Any more changes required?

2022-07-09 00:29 UTC, merged