Fixed responsiveness for footer component
service-mesh-performance/service-mesh-performance pull request #355
Opened 2022-08-25 23:56 UTC by neeraj-2

Signed-off-by: Neeraj Anand <neeraj.2@iitj.ac.in>

**Description**

This PR fixes #336. 
- Added some bootstrap inline styling for fixing the responsiveness of footer component

**Demo After Changes**

https://user-images.githubusercontent.com/56186425/186788761-f1993f42-6a0e-4f1a-88f5-f38a3bb73e64.mov

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-08-26 11:58 UTC, asubedy requested changes
Let's center align the Service Mesh Performance Heading and make it a little bigger in size
<img width="539" alt="image" src="https://user-images.githubusercontent.com/51183483/186898350-ec2674b7-c352-4b58-b7c9-c656d7d4265a.png">

2022-08-31 10:58 UTC, neeraj-2 commented
> Checking in... it has been awhile since we've heard from you on this issue. Are you still working on it? Please let us know and please don't hesitate to contact a [MeshMate](https://layer5.io/community/meshmates/) or any other [community member](https://layer5.io/community/members) for assistance.
> 
> > Be sure to [join the community](http://slack.layer5.io), if you haven't yet and please leave a star [star on the project](../stargazers) smile on the project.

Actually, the minor exams for my 7th sem are going on. So, I will continue from the 4th of September. Thanks!

2022-09-05 16:35 UTC, neeraj-2 commented
> Let's center align the Service Mesh Performance Heading and make it a little bigger in size <img alt="image" width="539" src="https://user-images.githubusercontent.com/51183483/186898350-ec2674b7-c352-4b58-b7c9-c656d7d4265a.png">

Thanks, @asubedy for your review and suggestion. I have pushed the changes. Sorry for being late. Actually, my exams were going on. Will be more regular from onwards. Thanks!

2022-09-05 18:22 UTC, asubedy commented on docs/_includes/footer.html
> +            <h6 class="rspnsv" style="color: #fff; font-weight: 600; text-align: center; font-size: medium;">Service Mesh Performance</h6>
```suggestion
            <h6 class="rspnsv" style="color: #fff; font-weight: 600; text-align: center; font-size: larger;">Service Mesh Performance</h6>
```

2022-09-05 19:01 UTC, asubedy approved these changes

2022-09-05 19:33 UTC, merged